# Generated by Django 3.0.5 on 2022-05-04 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmac', models.CharField(max_length=2000)),
                ('shop', models.CharField(max_length=2000)),
                ('code', models.CharField(max_length=2000)),
                ('access_token', models.CharField(max_length=2000)),
                ('install_date', models.DateTimeField(default=datetime.datetime(2022, 5, 4, 22, 48, 18, 612546))),
            ],
        ),
        migrations.CreateModel(
            name='product_detailmst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=50)),
                ('variant_id', models.CharField(max_length=60)),
                ('product_title', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('product_img', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
